function createfigure(X1, YMatrix1)
%CREATEFIGURE(X1, YMatrix1)
%  X1:  vector of x data
%  YMATRIX1:  matrix of y data

%  Auto-generated by MATLAB on 31-Jul-2023 16:04:42

% Create figure
figure1 = figure('Color',[1 1 1]);

% Create axes
axes1 = axes('Parent',figure1);
hold(axes1,'on');

% Create multiple lines using matrix input to plot
plot1 = plot(X1,YMatrix1,'MarkerSize',10,'LineStyle','--','Parent',axes1);
set(plot1(1),'DisplayName','Rojo','MarkerFaceColor',[1 0 0],'Marker','*',...
    'Color',[1 0 0]);
set(plot1(2),'DisplayName','Verde','MarkerFaceColor',[0 1 0],'Marker','o',...
    'Color',[0 1 0]);
set(plot1(3),'DisplayName','Azul','MarkerFaceColor',[0 0 1],...
    'Marker','square',...
    'Color',[0 0 1]);

% Create ylabel
ylabel('Amplitud (V)');

% Create xlabel
xlabel('Distancia (mm)');

% Uncomment the following line to preserve the X-limits of the axes
% xlim(axes1,[-0.141129032258061 139.858870967742]);
% Uncomment the following line to preserve the Y-limits of the axes
% ylim(axes1,[0 4.5]);
hold(axes1,'off');
% Set the remaining axes properties
set(axes1,'FontSize',14,'XGrid','on','YGrid','on');
% Create legend
legend(axes1,'show');

